{
 "title": "Terazo Parcel Service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Processed / Total Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(processed_by_request{status=\"processed\"})",
     "legendFormat": "success"
    },
    {
     "expr": "sum(processed_by_request{status=\"error\"})",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(processed_by_request)" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(processed_by_request[1m]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(processed_by_request{status=\"error\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(processed_by_request{status=\"error\"}[1m]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(processed_by_customer[1m]))",
     "legendFormat": "Throughput (Last 1m)"
    }
   ]
  },
  {
   "title": "Requests by Requestor Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "expr": "processed_by_request{status=\"processed\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Errors by Requestor Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "expr": "processed_by_request{status=\"error\"}",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Requests by Pickup Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "expr": "processed_by_customer{status=\"processed\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Errors by Pickup Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "valueName": "current",
   "targets": [
    {
     "expr": "processed_by_customer{status=\"error\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Throughput by Customer",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (customerName) (rate(processed_by_customer[1m]))",
     "legendFormat": "{{customerName}}"
    }
   ]
  },
  {
   "title": "Error Rate by Customer",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (customerName) (rate(processed_by_customer{status=\"error\"}[1m])) / sum by (customerName) (rate(processed_by_customer[1m]))",
     "legendFormat": "{{customerName}}"
    }
   ]
  },
  {
   "title": "Throughput by Pickup Region",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (region) (rate(processed_by_customer[1m]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Error Rate by Pickup Region",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (region) (rate(processed_by_customer{status=\"error\"}[1m])) / sum by (region) (rate(processed_by_customer[1m]))",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Error Rate by Pickup Region",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (region) (rate(processed_by_customer{status=\"error\"}[1m])) * 100 / sum by (region) (rate(processed_by_customer[1m]))",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}